#!/usr/bin/python

"""
Parse output generated by sweep_wcet.py.
"""

import glob
import re
import subprocess
import os

import matplotlib.pyplot as plot

# directory where simulation results are stored
log_dir = os.environ["GEM5"] + "/m5out/"

wcets = []
drops = []
not_drops = []
ticks = []

# For each log file
for filename in glob.glob(os.path.join(log_dir, "wcet*.log")):
  # Save WCET for this simulation run
  wcets.append(int(re.search("wcet([\d]*).log", filename).group(1)))
  log_file = open(filename, 'r')
  for line in log_file:
    # Find drops line
    drop_match = re.search("Drops = ([\d]*), Non-drops = ([\d]*)", line)
    if drop_match:
      drops.append(int(drop_match.group(1)))
      not_drops.append(int(drop_match.group(2)))
    # Find total ticks
    tick_match = re.search("Exiting @ tick ([\d]*)", line)
    if tick_match:
      ticks.append(int(tick_match.group(1))) 
  log_file.close()

print wcets
print drops

fig = plot.figure()

ax1 = plot.subplot(211)
ax1.scatter(wcets, drops)
ax1.scatter(wcets, not_drops, c='r')
plot.xlabel("WCET")
plot.ylabel("Drops")
plot.grid(True)
plot.legend(("Dropped", "Not dropped"), loc="upper left")

plot.subplot(212)
plot.scatter(wcets, ticks)
plot.xlabel("WCET")
plot.ylabel("Execution time")
plot.grid(True)

plot.show()
